### ISSUE TITLE
Getting forbidden for http://dl.bintray.com/steveliles/maven

### ISSUE THREAD

**Issue by ghost** [steveliles/opencv-android-3.0.0#7]
Hi Steve,
I am getting 403 forbidden error while trying to integrate your library in my app.  Earlier It was working fine but now throwing below error. Please provide some solution so that i could use this library in my app.
**Could not GET 'http://dl.bintray.com/steveliles/maven/org/opencv/OpenCV-Android/3.1.0/OpenCV-Android-3.1.0.pom'. Received status code 403 from server.**

**Comment by steveliles** [comment]
Unfortunately bintray has been sunsetted which is why the package is no longer accessible.

I'm snowed under with other things so it is unlikely i will get around to moving this package any time soon. I recommend looking for an alternative (and more up-to-date) build.

Alternatively, the README for the project has full instructions to build your own opencv package.

**Comment by ghost** [comment]
Thanks for your quick response :). I will try with alternative solution as per your README.

**Comment by gerardoepitacio** [comment]
@ajaykumar-kiwi Hi!, Did you find some alternative to this?.

Update

I hope it will help to somene.
https://github.com/gerardoepitacio/opencv-android-library

**Comment by ghost** [comment]
@gerardoepitacio Yes, I created my own gradle dependency through Jitpack. I just follow the steps written in Steve's readme. 

If you are using Steve's gradle dependency in your project then download Steve's project and create your own gradle dependency from Jitpack. You will not face any build error:)
